apiVersion: ha-operator.io/v1alpha1
kind: HomeAssistantInstance
metadata:
  name: home-assistant
spec:
  trustPodNetwork: {{ include "haso.trustPodNetwork" . }}
  {{- if ne .Values.ingress.trustedProxies nil }}
  httpProxy:
    trustedProxies: {{ .Values.ingress.trustedProxies | toJson }}
  {{- end }}
  desiredState: Running
  ownership: {{ .Values.ownership | quote }}
  options: {timezone: UTC, country: US, port: 80, ssl: false, diagnostics: false}
