apiVersion: v1
kind: ServiceAccount
metadata:
  name: supervisor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: supervisor
rules:
  - apiGroups: [ha-operator.io]
    resources: [homeassistantinstances]
    resourceNames: [home-assistant]
    verbs: [get, update]
  - apiGroups: [ha-operator.io]
    resources: [homeassistantinstances]
    verbs: [list, watch]
  - apiGroups: [ha-operator.io]
    resources: [homeassistantinstances/status]
    resourceNames: [home-assistant]
    verbs: [get, update]
  - apiGroups: [ha-operator.io]
    resources: [homeassistantoperations, homeassistantoperations/status]
    verbs: [get, list, create, update, delete]
  - apiGroups: [apps]
    resources: [statefulsets]
    resourceNames: [core]
    verbs: [get, update, delete]
  - apiGroups: [apps]
    resources: [statefulsets]
    verbs: [create]
  - apiGroups: ['']
    resources: [configmaps]
    resourceNames: [core-workload]
    verbs: [get]
  - apiGroups: ['']
    resources: [pods]
    resourceNames: [core-0]
    verbs: [get]
  - apiGroups: ['']
    resources: [pods/exec]
    resourceNames: [core-0]
    verbs: [get, create]
  - apiGroups: ['']
    resources: [pods/log]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: supervisor
subjects:
  - {kind: ServiceAccount, name: supervisor, namespace: {{ .Release.Namespace }}}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: supervisor}
